sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t yatinqss/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true yatinqss/react-test npm test

after_success:
  - docker build -t yatinqss/multi-client ./client
  - docker build -t yatinqss/multi-server ./server
  - docker build -t yatinqss/multi-worker ./worker
  - docker build -t yatinqss/multi-nginx ./nginx